mid_install_zip: "mid.trackitomgold-04-17-2015_02-29-2016_1827.linux.x86-64.zip"
mid_instance_url: <sn_instance_url> 
mid_instance_user: <sn_user> 
mid_instance_pass: <sn_pass>
mid_instance_name: <sn_mid_name> 
